[window]
opacity = 0.8
blur = true
decorations = "none"

[window.padding]
x = 0
y = 0

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"

[mouse]
hide_when_typing = true

[font.normal]
family = "BlexMono Nerd Font Mono"
# family = "FiraCode Nerd Font"
# family = "ComicShannsMono Nerd Font"

[colors.primary]
background = "0x282828"
foreground = "0xdfbf8e"

[colors.normal]
black = "0x665c54"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe78a4e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

# Bright colors
[colors.bright]
black = "0x928374"
red = "0xea6962"
green = "0xa9b665"
yellow = "0xe3a84e"
blue = "0x7daea3"
magenta = "0xd3869b"
cyan = "0x89b482"
white = "0xdfbf8e"

[cursor.style]
shape = "Beam"
blinking = "Off"

[shell]
program = "zsh"
args = ["-l", '-c', 'tmux new-session']
