#!/usr/bin/env bash

if [ -n "$WAYLAND_DISPLAY" ]; then
    selected=$(nix search nixpkgs ^ --json | jq -r 'to_entries[] | [(.key | split(".") | .[-1]), .value.pname, .value.version, .value.description] | @tsv' | rofi -dmenu -p "nix search")
else
    selected=$(nix search nixpkgs ^ --json | jq -r 'to_entries[] | [(.key | split(".") | .[-1]), .value.pname, .value.version, .value.description] | @tsv' | fzf --prompt="nix search " --preview "echo {}" )
fi

pkgname=$(echo $selected | awk '{print $1}')

if [ -z "${pkgname}" ]; then
	# No package selected
	exit 1
fi

echo "$pkgname"
