[helpers]

[default]
depends = ["alacritty", "nvim", "tmux", "sway", "rofi"]

[default.files]
[default.variables]


[alacritty.files]
alacritty = "~/.config/alacritty"

[nvim.files]
nvim = "~/.config/nvim"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[sway.files]
sway = "~/.config/sway/"

[rofi.files]
rofi = "~/.config/rofi/"
