[helpers]

[default]
depends = [
	"nvim",
	"tmux",
	"sway",
	"swaync",
	"swaylock",
	"waybar",
	"rofi",
	"dunst",
	"darkman",
	"xdg-desktop-portal",
]

[default.files]
[default.variables]

[legacy]
depends = ["alacritty"]

[alacritty.files]
alacritty = "~/.config/alacritty"

[nvim.files]
nvim = "~/.config/nvim"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"

[sway.files]
sway = "~/.config/sway/"

[swaync.files]
swaync = "~/.config/swaync/"

[swaylock.files]
swaylock = "~/.config/swaylock/"

[waybar.files]
waybar = { target = "~/.config/waybar/", type = "symbolic" }

[rofi.files]
rofi = "~/.config/rofi/"

[dunst.files]
dunst = "~/.config/dunst/"

[sddm-theme.files]
"sddm/themes" = { target = "/etc/sddm/themes", type = "template", owner = "root" }

[sddm-conf.files]
"sddm/config.d" = { target = "/etc/sddm.conf.d/", type = "template", owner = "root" }

[darkman.files]
darkman = "~/.config/darkman"

[xdg-desktop-portal.files]
xdg-desktop-portal = "~/.config/xdg-desktop-portal"

[nixos.files]
nixos = { target = "/etc/nixos", type = "template", owner = "root" }
