[helpers]

[default]
depends = ["alacritty", "nvim", "tmux"]

[default.files]
[default.variables]


[alacritty.files]
alacritty = "~/.config/alacritty"

[nvim.files]
nvim = "~/.config/nvim"

[tmux.files]
"tmux/.tmux.conf" = "~/.tmux.conf"
